Repository OpenAstronomy/openastronomy.github.io, pull requests merged in 2022-02, with the labels that each got.

#299 sunpy 2022 gsoc projects
  _projects/2022/sunpy/database.md
  _projects/2022/sunpy/helioviewer.md
  _projects/2022/sunpy/scraper.md
Labels: GSOC

#300 Bayesian Excess Variance (bexvar) in Stingray
  _projects/2022/stingray/bexvar.md
Labels: GSOC

#303 Update comm links
  _includes/footer.html
  _projects/README.md
  gsoc/display/data/faq/contact_mentor.md
  gsoc/student_guidelines.md
  index.md
Labels: GSOC, Organisations

#304 Updates checks to ignore out-to-date links
  .circleci/config.yml
  gsoc/background.md
  gsoc/student_guidelines.md
  gsoc/suborg_guidelines.md
Labels: enhancement
